spring:
  application:
    name: scargo

  # PostgreSQL 연결 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/scargo
    username: postgres
    password: '1234'
    driver-class-name: org.postgresql.Driver

  # JPA 및 Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true